### ISSUE TITLE
Fix return url and success page

### ISSUE THREAD

**Issue by daichety** [zurianalytics/zurianalytics#18]
- [x] **Manage subscription** - when managing subsription and returning, now leading to test.api.etf-data.com

![image](https://user-images.githubusercontent.com/63511071/86487540-a7528500-bd5e-11ea-9e1d-8949c1a52032.png)

- [x] **Success page** - currently under localhost

![image](https://user-images.githubusercontent.com/63511071/86487730-2e9ff880-bd5f-11ea-9f3d-4057b32d5894.png)

**Comment by sdoncho** [comment]
Ready to test
